import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import GlobalState from "./context/CartContext";
import PageState from "./context/PageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PageState>
        <GlobalState>
          <body className={inter.className}>
            <Header />
            <div className="container">{children}</div>
          </body>
        </GlobalState>
      </PageState>
    </html>
  );
}
